version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: birdy-messages
    restart: unless-stopped
    environment:
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27018
      - MONGO_DB=birdy-messages
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

  db:
    image: mongo:4.1.8-xenial
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  